version: '3.4'

services:
  permissionmanagementdb:
    container_name: permissionmanagementdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GfD12345678
    restart: always
    ports:
      - "1433:1433"

  permissionmanagementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=permissionmanagementdb;Database=PermissionManagementDb;User Id=sa;Password=GfD12345678;Encrypt=False;TrustServerCertificate=True
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - permissionmanagementdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601