version: '3.4'

services:
  permissionmanagementdb:
    image: mcr.microsoft.com/mssql/server
 
  permissionmanagementapi:
    image: ${DOCKER_REGISTRY-}permissionmanagementapi
    build:
      context: .
      dockerfile: Services/PermissionManagement/PermissionManagementAPI/Dockerfile
